# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  phpstan:
    name: PHPStan + PHPUnit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: PHPStan
      uses: docker://oskarstark/phpstan-ga   
      env:
        REQUIRE_DEV: true
      with:
        args: analyse

    - name: PHPUnit (php-actions)
      uses: php-actions/phpunit@v9
