# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on every push
on: push

jobs:
  run:

    strategy:
      matrix:
        php-version:
          - "8.2"
          - "8.3"
          - "8.4"
        operating-system:
          - ubuntu-latest
          - windows-latest

    runs-on: ${{ matrix.operating-system }}

    name: Analyse and test code (PHP ${{ matrix.php-version }}, ${{ matrix.operating-system }})

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: "${{ matrix.php-version }}"
        extensions: sqlite, pdo_sqlite, fileinfo

    - name: Get composer cache directory
      id: composercache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ${{ steps.composercache.outputs.dir }}
        key: php-${{ matrix.php-version }}-composer-${{ hashFiles('**/composer.json') }}
        restore-keys: php-${{ matrix.php-version }}-composer-

    - name: Install dependencies
      run: composer update --no-interaction --no-progress

    - name: PHPStan
      run: vendor/bin/phpstan analyse

    - name: PHPUnit
      run: vendor/bin/phpunit
